package M1.Systeme_Simple_CS.Composant_Serveur.Configuration_Serveur_Detail.Composant_Connection_Manager;

import M2.Objet_Architectural.Interface_Communication.Port_Composant_Fourni;

public class External_Socket extends Port_Composant_Fourni {

}
