package M1.Systeme_Simple_CS.Composant_Serveur.Configuration_Serveur_Detail.Composant_Security_Manager;

import M2.Objet_Architectural.Interface_Communication.Port_Composant_Fourni;

public class Receive_Security_Auth extends Port_Composant_Fourni {

}
